---
- name: Verificar existência das filas
  hosts: localhost
  gather_facts: no
  vars:
    queues_to_check:
      - queue1
      - queue2
      - queue3
    teams_webhook_url: "{{ teams_webhook_url }}"
  tasks:
    - name: Verificar existência das filas
      uri:
        url: "{{ rabbitmq_url }}/rabbitmq/api/queues/"
        method: GET
        headers:
          Authorization: "{{ credentials }}"
        return_content: yes
      register: queues_response

    - set_fact:
        existing_queues: "{{ queues_response.json | map(attribute='name') | list }}"

    - name: Enviar notificação para o Teams
      uri:
        url: "{{ teams_webhook_url }}"
        method: POST
        body_format: json
        body: |
          {
            "text": "{% for queue in queues_to_check if queue not in existing_queues %}A fila {{ queue }} não existe.{% endfor %}"
          }
      register: webhook_response
      when: queues_to_check | difference(existing_queues) | length > 0

    - debug:
        var: webhook_response
